name: Publish

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: bootJar
      - name: Deploy to prod
        env:
          deployUser: ${{ secrets.CLOJARS_USER }}
          deployToken: ${{ secrets.CLOJARS_TOKEN }}
        run: |
          sshpass -v -p ${{ secrets.DEPLOY_PASSWORD }} scp -o StrictHostKeyChecking=no -P ${{ secrets.DEPLOY_PORT }} ${{ github.workspace }}/build/libs/backend.jar ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:/home/dynomake/vpn/